import { P00QuestionDef } from "./p00-questions";

export const P04M_QUESTIONS: P00QuestionDef[] = [
  {
    key: "mobile.frameworkChoice",
    label: "Pilihan Framework Mobile",
    group: "constraints_context",
    groupTitle: "Pondasi Platform Mobile",
    description: "Framework atau bahasa pemrograman untuk pengembangan aplikasi mobile.",
    placeholder: "Contoh: Flutter (Dart), React Native / Expo (TypeScript), Kotlin Native Android",
    example: "Flutter untuk single codebase Android & iOS",
    required: false,
    valueType: "string",
    defaultCertainty: "confirmed",
    helpText: "AI akan menyusun arsitektur dan konvensi folder spesifik framework tersebut.",
  },
  {
    key: "mobile.offlineSyncStrategy",
    label: "Strategi Penyimpanan Lokal & Mode Offline",
    group: "constraints_context",
    groupTitle: "Data & Offline",
    description: "Kebutuhan database lokal di perangkat dan sinkronisasi data.",
    placeholder: "Contoh: SQLite / Hive / Room / SharedPreferences, full offline-first",
    example: "Offline-first dengan SQLite lokal; ekspor/impor file JSON",
    required: false,
    valueType: "string",
    defaultCertainty: "confirmed",
    helpText: "Membantu AI merancang arsitektur repository lokal dan penanganan kehilangan sinyal.",
  },
  {
    key: "mobile.devicePermissions",
    label: "Izin Perangkat (Permissions)",
    group: "constraints_context",
    groupTitle: "Kemampuan Perangkat",
    description: "Fitur hardware atau izin OS yang harus diakses aplikasi.",
    placeholder: "Contoh: Kamera, Notifikasi lokal, Bluetooth printer, Storage file",
    example: "Hanya notifikasi lokal dan izin baca/tulis penyimpanan berkas",
    required: false,
    valueType: "string",
    defaultCertainty: "preference",
    helpText: "AI akan merancang alur runtime permission request dan fallback jika ditolak.",
  },
  {
    key: "mobile.targetStores",
    label: "Target Distribusi Toko Aplikasi",
    group: "constraints_context",
    groupTitle: "Distribusi",
    description: "Kanal distribusi aplikasi mobile yang direncanakan.",
    placeholder: "Contoh: Google Play Store, Apple App Store, internal testing APK",
    example: "Google Play Store (AAB release) dan distribusi langsung APK",
    required: false,
    valueType: "string",
    defaultCertainty: "confirmed",
    helpText: "Menentukan panduan penandatanganan sertifikat rilis dan kebijakan review toko aplikasi.",
  },
];
