import { P00QuestionDef } from "./p00-questions";

export const P04W_QUESTIONS: P00QuestionDef[] = [
  {
    key: "web.renderingModel",
    label: "Model Rendering Web",
    group: "constraints_context",
    groupTitle: "Arsitektur Frontend Web",
    description: "Pendekatan rendering halaman web utama (SPA, SSR, SSG, Static).",
    placeholder: "Contoh: Single Page App (Vite/React) atau Server-Side Rendering (Next.js)",
    example: "Next.js App Router dengan Static Site Generation & Server Components",
    required: false,
    valueType: "string",
    defaultCertainty: "preference",
    helpText: "Mempengaruhi struktur routing, SEO, dan penanganan lifecycle data fetching.",
  },
  {
    key: "web.authStrategy",
    label: "Strategi Autentikasi & Sesi Web",
    group: "constraints_context",
    groupTitle: "Keamanan & Sesi",
    description: "Bagaimana pengguna login dan status sesi diverifikasi.",
    placeholder: "Contoh: HTTP-only Secure Cookies, JWT bearer token, NextAuth/Auth.js, atau Tanpa Login",
    example: "Tanpa login untuk MVP; data lokal di browser",
    required: false,
    valueType: "string",
    defaultCertainty: "confirmed",
    helpText: "Membantu AI merancang middleware keamanan dan perlindungan CSRF.",
  },
  {
    key: "web.stateManagement",
    label: "Pendekatan State Management",
    group: "constraints_context",
    groupTitle: "Manajemen Data Client",
    description: "Cara mengelola state lokal dan server di client web.",
    placeholder: "Contoh: React useState + Context API, Zustand, TanStack Query",
    example: "Zustand untuk client state + TanStack Query untuk API fetching",
    required: false,
    valueType: "string",
    defaultCertainty: "preference",
    helpText: "Mencegah duplikasi state dan pola arsitektur yang berantakan.",
  },
  {
    key: "web.deploymentTarget",
    label: "Target Hosting & Domain",
    group: "constraints_context",
    groupTitle: "Deployment & Rilis",
    description: "Target platform hosting untuk web.",
    placeholder: "Contoh: Vercel, Netlify, Cloudflare Pages, atau Docker di VPS",
    example: "Vercel Hobby Tier dengan custom domain",
    required: false,
    valueType: "string",
    defaultCertainty: "confirmed",
    helpText: "AI akan menyertakan instruksi build script dan environment variables.",
  },
];
